### ISSUE TITLE
Rotate webcam 90 degrees counter clockwise

### ISSUE THREAD

**Issue by alexisml** [fabianonline/OctoPrint-Telegram#146]
When you check "Rotate webcam 90 degrees counter clockwise" under OctoPrint settings (Webcam & Timelapse) the image that appears in the telegram chat is flipped 90 degrees (**NOT counter**) clockwise, so it shows the image upsidedown. This should be a simple fix.

![flipped](https://user-images.githubusercontent.com/16224395/43540393-feef0bc0-959d-11e8-9a97-ba26739a821b.PNG)

Environment info:
- Raspberry Pi 3+
- OctoPrint 1.3.9 running on OctoPi 0.15.1
- I'm using a raspberry camera (not usb)

**Comment by kaltgift** [comment]
I'd like to confirm, except I'm seeing this on a Logitech C270 usb camera.

Raspberry Pi 3+, OctoPrint 1.3.8 running on 0.14.0

**Comment by rlogiacco** [comment]
I've added a few log lines at debug level which are intended to track the image transformations: would you please enable debug logging of the plugin and report the values traced into the log?

It should look like:

```
2019-07-18 01:40:53,838 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-07-18 01:40:54,027 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]

```

**Comment by f4nu** [comment]
@derpicknicker1 the issue was reverted, why did you close it?
![image](https://user-images.githubusercontent.com/8605605/77833209-e3f95980-713b-11ea-9b57-678273387273.png)

As this issue is still live, can we reopen it? I'm seeing my webcam set up correctly in the _Control tab_ on Octoprint, but the images and GIFs I receive on Telegram are mirrored:

### Control tab
![image](https://user-images.githubusercontent.com/8605605/77833008-6ed95480-713a-11ea-9f75-1ad993bec0dc.png)

### Telegram
![image](https://user-images.githubusercontent.com/8605605/77833113-1fdfef00-713b-11ea-9734-ede5c91e1c73.png)

@rlogiacco I have collected the logs you put in previously:
```
2020-03-28 21:35:09,157 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2020-03-28 21:35:09,242 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:True]
```

I can confirm that the horizontal mirroring is indeed flipped; I activated it on Octoprint and the message sent on Telegram is inverted, although now correct.

![image](https://user-images.githubusercontent.com/8605605/77833323-c7a9ec80-713c-11ea-8b60-26e8de5a2bdf.png)

![image](https://user-images.githubusercontent.com/8605605/77833305-b1039580-713c-11ea-9054-535a2d50d909.png)

**Comment by codyg** [comment]
Can confirm I'm have the exact same problem! Looks right in Control looks 180 degrees off in Telegram.

**Comment by f4nu** [comment]
I just noticed that the vertical flipping is indeed also flipped.
