### ISSUE TITLE
Setup token shows up at every page refresh

### ISSUE THREAD

**Issue by tyleraharrison** [fabianonline/OctoPrint-Telegram#180]
Have used this plugin forever, today I reflashed the OctoPi SD card and installed this plugin and everything works flawlessly except for when I refresh the page I always get the token setup popup. Easily fixable by just hitting next but it's definitely annoying. It always says the token status is unknown until I check it, when it says its working just fine.

**Comment by Quintin9801** [comment]
Having the exact same problem using OctoPrint on Windows instead of Pi

**Comment by raidolo** [comment]
Same here, when I restart Octoprint (on docker) the wizard popup appear asking to verify the Token.

**Comment by gatescs** [comment]
I just set up this plugin today and I am having the same issue.  Has anyone made any progress on resolving this?

**Comment by raidolo** [comment]
For me the problem was the original Octo instance still running. Somehow when you have the plugin already started elsewhere and the bot is connected to the first instance, you can’t initiate another session properly, maybe because I was using the same chat id and the first instance “listens” for incoming messages, so the second instance could not be initiated properly. (when you use this kind of bots the plugins are always in listening mode checking for incoming messages, I didn’t check the pluginsource, but I guess it’s not different)

**Comment by rlogiacco** [comment]
One code == one plugin instance

A second instance using the same code automatically kicks the second out of
play

Il giorno lun 30 set 2019 alle 01:33 raidolo <notifications@github.com> ha
scritto:

**Comment by gatescs** [comment]
Thank you for the reply.  I think I follow what you are saying, I am new to this plugin, so still learning.  So, for example, if I have multiple printers, each with their own Pi, each using Telegram, should I create a new bot for each?  Right now, I have two printers/Pi's running Telegram to test it out, but they are both using the same.  Which is likely creating the problem as you noted.

Thanks again, very much appreciated.

**Comment by rlogiacco** [comment]
If you want to tell printer 1 to start printing model A and tell printer 2
to abort the print you need to “chat” with two separate bots... this
requires to create 2 bots, each one identifying a printer.

1 bot == 1 printer

Makes sense now?

Il giorno lun 30 set 2019 alle 14:57 gatescs <notifications@github.com> ha
scritto:

**Comment by rlogiacco** [comment]
Glad to hear that
